name: Bug Report
description: Report a bug in DockedUp
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug in DockedUp! Please provide details to help us diagnose and fix the issue.
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear description of the bug, including what you expected and what happened.
      placeholder: "When I press 'l' to view logs, DockedUp crashes with an error..."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the bug.
      placeholder: |
        1. Run `dockedup --refresh 0.5`
        2. Select a container with arrow keys
        3. Press 'l' to view logs
        4. Observe crash
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide details about your setup.
      placeholder: |
        - OS: [e.g., Ubuntu 22.04]
        - Python Version: [e.g., 3.10.12]
        - Docker Version: [e.g., 20.10.7]
        - DockedUp Version: [e.g., 0.1.0]
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or Error Messages
      description: Share relevant logs or error messages (run `dockedup --debug` if needed).
      placeholder: "Traceback (most recent call last): ..."
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other details or screenshots (e.g., DockedUp UI).
      placeholder: "This happens only with remote Docker hosts."